import MyContext from "@/helper/Context";
import "./globals.css";

export const metadata = {
  title: "Muneeb's 2nd  Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning >
        <MyContext>
          {children}
        </MyContext>
      </body>
    </html>
  );
}
